sudo: required

language: python

services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  docker build -t harryjubb/arpeggio .

script:
  # SMOKE TEST
  - docker run --rm -it harryjubb/arpeggio python arpeggio.py -h
